### ISSUE TITLE
Question about Caveats - "not a production reference"

### ISSUE THREAD

**Issue by balazsdukai** [andyburgin/hadoopi#8]
First of all, thank you for the excellent material!
I've been considering since awhile to set up Raspberry cluster, just as you did, for 

+ learning distributed application development,
+ learning about the inner workings of Hadoop configuration (just as you mentioned).

So far I did a couple of online courses on distributed data processing with Hadoop and such, and I'm able write basic analysis workflows in Hadoop MapReduce, Spark. But I've never actually ran anything in a production environment, neither am I familiar with any of the ecosystems of the big cloud providers (Cloudera, AWS etc).

I imagine that with a Raspberry cluster I would have access to a learning/development environment that mirrors a production environment 1-to-1, or at least veeery closely :-). In other words, if I develop a distributed process on the Raspberry cluster, I'll be able to run it on a "real" cluster at one of the cloud providers with much more data, and the job will succeed just as on the Raspberry cluster. Is this true? Or reasonable to expect? (provided that there are no surprises in the data for which I didn't account for)

Thus I'm very curious what do you mean by *"you really wouldn't want to run anything "real" on there."*, when you describe the caveats? Do you mean "real" as in processing realistically large amount of data, or "real" as in the Raspberry cluster doesn't actually mirror the behavior of a real cluster, thus not really suitable for developing distributed applications?

**Comment by andyburgin** [comment]
Hi Balázs, the pi only has a gig of ram and by modern standards is an old slow ARM architecture. The project is more designed as a learning tool for setting up the cluster and running simple demo apps. 

For any significant amount of data processing you'll probably just end up being incredibly frustrated as your workloads may just fail due to lack of memory.  If you want to run things on hadoop as opposed to run hadoop you would be better investing the funds to build a Pi cluster with AWS credits and learning how to run your workloads there.

**Comment by balazsdukai** [comment]
Hi Andy, thank you for the insight and advice! I briefly looked into what AWS offers for learning and it indeed seems a viable option. Plus the knowledge of some of the AWS services is valuable skill to have.
